### ISSUE TITLE
Does not work with QGIS 3

### ISSUE THREAD

**Issue by rgzn** [nejcd/LidarSloveniaDataDownloader#8]
Looks like this project is still in python 2? Any plans to update?

**Comment by johanjohan** [comment]
had the same yesterday. the branch feature/qgis3 works for me QGIS 3.10

**Comment by nejcd** [comment]
@rgzn  branch feature/qgis3 should work. Currently, I have only tested it only on osx. 
@johanjohan may I ask with on witch OS have you use it?

Currently, there are still some bugs with notifications. I hope I will find some time next month, to test it merge it to master and published it to the Qgis plugin repository.

**Comment by rgzn** [comment]
Thanks!

**Comment by johanjohan** [comment]
@nejcd  Hi, i am on windows 10, thank you for the plugin.
